# Generated by Django 5.2.12 on 2026-04-01 08:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('changed_by', models.CharField(max_length=100, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('grade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gradeitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_history_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
